# Generated by Django 5.1.3 on 2024-12-24 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategoriesModel',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_name', models.CharField(max_length=25)),
                ('fee_type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentsDataModel',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=10)),
                ('roll_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=5)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField()),
                ('amount_paid', models.IntegerField()),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.feecategoriesmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.studentsdatamodel')),
            ],
        ),
    ]
