# Generated by Django 5.1.3 on 2024-12-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_studentfeesmodel_amount_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeesmodel',
            name='amount_due',
        ),
    ]
